"""
CRUCIBLE :: materialize.py

The output of a successful run is not "it worked on my machine." It is a
*recipe*, emitted in formats that outlive the tool:

    Dockerfile          runs anywhere, needs nothing from us
    compose.yml         app + the sidecars we discovered it needed
    crucible.lock.json  the full plan with provenance for every decision

This is the difference between a demo and infrastructure. A tool that can
only tell you "yes it runs" is a toy. A tool that hands you a Dockerfile
derived from *observed* success -- every package in it justified by a real
failure it fixed -- has produced something durable, and something a human
can review line by line.
"""

from __future__ import annotations

import json
from dataclasses import asdict

from .schema import RunPlan


def to_dockerfile(plan: RunPlan) -> str:
    L = [
        "# Generated by CRUCIBLE from an observed successful run.",
        "# Every line below was validated by execution, not inferred.",
        "#",
    ]
    for note in plan.provenance:
        L.append(f"#   · {note}")
    L += ["", f"FROM {plan.base}", ""]

    if plan.system_packages:
        pkgs = " \\\n        ".join(sorted(plan.system_packages))
        L += ["RUN apt-get update \\",
              "    && apt-get install -y --no-install-recommends \\",
              f"        {pkgs} \\",
              "    && rm -rf /var/lib/apt/lists/*", ""]

    for k, v in sorted(plan.env.items()):
        if k.startswith("CRUCIBLE_"):
            continue
        L.append(f"ENV {k}={_q(v)}")
    if plan.env:
        L.append("")

    L += [f"WORKDIR /app/{plan.workdir.strip('./')}".rstrip("/"), "", "COPY . /app", ""]

    for s in plan.steps:
        cwd = f"cd {s.cwd} && " if s.cwd not in (".", "", "./") else ""
        L.append(f"# {s.name}")
        L.append(f"RUN {cwd}{s.cmd}")
        L.append("")

    for p in plan.ports:
        L.append(f"EXPOSE {p}")
    if plan.ports:
        L.append("")

    if plan.run:
        L.append(f'CMD ["sh", "-c", {json.dumps(plan.run)}]')
    return "\n".join(L) + "\n"


_LOOPBACK = ("127.0.0.1", "localhost", "0.0.0.0", "[::1]", "::1")


def compose_host_rewrite(value: str, services) -> str:
    """Loopback is correct in the pod and wrong in compose.

    CRUCIBLE boots the app and its sidecars into one shared network namespace,
    so the app reaches postgres on `127.0.0.1:5432` -- that is the entire point
    of the pod model, and the env that verified the run says exactly that.
    Compose gives every service its own namespace and resolves peers by service
    name. Emitting the verified env verbatim therefore produces a compose file
    that cannot connect to anything it declares, which is a bad failure for an
    artifact whose selling point is that it was validated by execution.

    Only ports belonging to a declared sidecar are rewritten; the app's own
    port stays loopback.
    """
    for svc in services:
        for port in svc.ports:
            for host in _LOOPBACK:
                value = value.replace(f"{host}:{port}", f"{svc.name}:{port}")
    return value


def to_compose(plan: RunPlan, name: str = "app") -> str:
    L = ["# Generated by CRUCIBLE. Sidecars below were detected from source",
         "# and confirmed necessary by a failed connection during verification.",
         "services:", f"  {name}:", "    build: .",]
    if plan.ports:
        L.append("    ports:")
        for p in plan.ports:
            L.append(f'      - "{p}:{p}"')
    env = {k: v for k, v in plan.env.items() if not k.startswith("CRUCIBLE_")}
    if env:
        L.append("    environment:")
        for k, v in sorted(env.items()):
            L.append(f"      {k}: {_yq(compose_host_rewrite(str(v), plan.services))}")
    if plan.services:
        L.append("    depends_on:")
        for s in plan.services:
            L.append(f"      - {s.name}")
    for s in plan.services:
        L += [f"  {s.name}:", f"    image: {s.image}"]
        if s.ports:
            L.append("    ports:")
            for p in s.ports:
                L.append(f'      - "{p}:{p}"')
        if s.env:
            L.append("    environment:")
            for k, v in sorted(s.env.items()):
                L.append(f"      {k}: {_yq(v)}")
    return "\n".join(L) + "\n"


def to_lock(plan: RunPlan, evidence_fp: str, attempts: list, ledger=None) -> str:
    return json.dumps({
        "egress": ({"build_hostnames": ledger.hostnames,
                    "build_peers": [f"{i}:{p}" for i, p in ledger.peers],
                    "build_peers_never_resolved": [f"{i}:{p}" for i, p in ledger.unresolved],
                    "runtime_egress_possible": ledger.runtime_egress_possible}
                   if ledger is not None else None),
        "version": 1,
        "evidence_shape": evidence_fp,
        "plan_fingerprint": plan.fingerprint(),
        "repairs_applied": plan.generation,
        "attempts": [asdict(a) for a in attempts],
        "plan": asdict(plan),
    }, indent=2) + "\n"


def _q(v: str) -> str:
    return json.dumps(str(v)) if (" " in str(v) or not v) else str(v)


def _yq(v: str) -> str:
    s = str(v)
    return json.dumps(s) if (s == "" or s[0] in "{[*&!|>%@`" or ": " in s or "#" in s) else s
